// tradeflow-web-next/src/components/product/product-grid.tsx
"use client"

import { useMemo } from "react"
import { AlertTriangle, CheckCircle2, Clock3, ShoppingBag } from "lucide-react"

import { useAppI18n } from "@/components/layout/locale-provider"
import { ProductCard } from "@/components/product/product-card"
import { ImageWithFallback } from "@/components/ui/image-with-fallback"
import { Card, CardContent } from "@/components/ui/card"
import { getReadableOriginalTitle, getReadableProductName, getReadableStageLabel, humanizeQualityTier, humanizeReportSource } from "@/lib/presentation"
import { useTaskRunner } from "@/hooks/use-task-runner"
import { getFilteredCandidates, useProductsStore } from "@/stores/products-store"
import { useTaskStore } from "@/stores/task-store"

export function ProductGrid() {
  const { t } = useAppI18n()
  const productState = useProductsStore()
  const candidates = useMemo(() => getFilteredCandidates(productState), [productState])
  const selectedProductId = useProductsStore((state) => state.selectedProductId)
  const isLoading = useProductsStore((state) => state.isLoading)
  const isAnalyzingReport = useProductsStore((state) => state.isAnalyzingReport)
  const status = useTaskStore((state) => state.status)
  const stage = useTaskStore((state) => state.stage)
  const isPolling = useTaskStore((state) => state.isPolling)
  const { analyzeProduct } = useTaskRunner()

  const currentCandidate = useMemo(() => {
    if (!selectedProductId) return null
    return productState.candidates.find((item) => item.productId === selectedProductId) ?? null
  }, [productState.candidates, selectedProductId])
  const currentReport = useMemo(() => {
    if (!selectedProductId) return null
    return productState.reportsByProductId[selectedProductId] ?? null
  }, [productState.reportsByProductId, selectedProductId])

  const workflowSteps = useMemo(() => {
    const hasCandidates = candidates.length > 0
    const hasSelection = Boolean(selectedProductId)
    return [
      { key: "discover", title: t("productGrid.step1"), state: hasCandidates ? "complete" : isPolling ? "active" : "pending" },
      { key: "select", title: t("productGrid.step2"), state: hasSelection ? "complete" : hasCandidates ? "active" : "pending" },
      { key: "report", title: t("productGrid.step3"), state: isAnalyzingReport ? "active" : status === "REPORT_READY" ? "complete" : "pending" },
    ] as const
  }, [candidates.length, isAnalyzingReport, isPolling, selectedProductId, status, t])

  const currentReportBadges = useMemo(() => {
    const provenance = currentReport?.provenance
    if (!provenance) return []
    return [
      provenance.qualityTier
        ? { key: "quality", value: humanizeQualityTier(provenance.qualityTier, t) }
        : null,
      provenance.retrievalSource
        ? { key: "retrieval", value: humanizeReportSource(provenance.retrievalSource, t) }
        : null,
      provenance.detailSource
        ? { key: "detail", value: humanizeReportSource(provenance.detailSource, t) }
        : null,
      { key: "fallback", value: provenance.fallbackUsed ? t("common.yes") : t("common.no") },
    ].filter((item): item is { key: string; value: string } => Boolean(item))
  }, [currentReport?.provenance, t])

  const processBanner = useMemo(() => {
    if (status === "WAITING_1688_VERIFICATION") {
      return {
        tone: "warning" as const,
        title: t("productGrid.bannerVerificationTitle"),
        description: t("productGrid.bannerVerificationDescription"),
      }
    }

    if (status === "REPORT_READY" && currentCandidate) {
      return {
        tone: "success" as const,
        title: t("productGrid.bannerReportReadyTitle"),
        description: t("productGrid.bannerReportReadyDescription", {
          title: getReadableProductName(currentCandidate.title),
        }),
      }
    }

    if (isAnalyzingReport && currentCandidate) {
      return {
        tone: "info" as const,
        title: t("productGrid.bannerAnalyzingTitle"),
        description: t("productGrid.bannerAnalyzingDescription", {
          title: getReadableProductName(currentCandidate.title),
        }),
      }
    }

    if (status === "WAITING_USER_SELECTION" && candidates.length > 0) {
      return {
        tone: "info" as const,
        title: t("productGrid.bannerSelectionTitle"),
        description: t("productGrid.bannerSelectionDescription"),
      }
    }

    if ((isLoading || isPolling) && candidates.length === 0) {
      return {
        tone: "info" as const,
        title: t("productGrid.bannerDiscoveryTitle"),
        description: t("productGrid.bannerDiscoveryDescription"),
      }
    }

    return null
  }, [candidates.length, currentCandidate, isAnalyzingReport, isLoading, isPolling, status, t])

  return (
    <div className="flex h-full min-h-0 flex-col">
      <div className="border-b border-[var(--tf-border)] px-4 py-3">
        <div className="flex items-start justify-between gap-4">
          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <ShoppingBag className="size-5 text-[var(--tf-text-subtle)]" />
              <h2 className="text-lg font-semibold text-[var(--tf-text)]">{t("productGrid.title")}</h2>
              <span className="shrink-0 text-sm text-[var(--tf-text-subtle)]">{t("productGrid.results", { count: candidates.length })}</span>
            </div>
            <p className="mt-1 text-xs leading-5 text-[var(--tf-text-muted)]">{t("productGrid.subtitle")}</p>
          </div>
          <span className="shrink-0 rounded-full border border-[var(--tf-border)] px-3 py-1 text-xs text-[var(--tf-text-muted)]">{getReadableStageLabel(stage)}</span>
        </div>

          <div className="mt-3 grid gap-2 md:grid-cols-3">
            {workflowSteps.map((step, index) => (
              <Card
                key={step.key}
                className={
                  step.state === "complete"
                  ? "tf-step-complete border-emerald-300 bg-emerald-50 shadow-[inset_0_0_0_1px_rgba(16,185,129,0.15)] transition-colors duration-300"
                  : step.state === "active"
                    ? "tf-step-active border-blue-300 bg-blue-50 shadow-[inset_0_0_0_1px_rgba(59,130,246,0.18)] transition-all duration-300"
                    : "border-[var(--tf-border)] bg-white transition-colors duration-300"
                }
              >
              <CardContent className="p-3">
                <div className="flex items-center gap-3">
                  <span
                    className={
                      step.state === "complete"
                        ? "flex size-7 items-center justify-center rounded-full bg-emerald-500 text-[11px] font-semibold text-white"
                        : step.state === "active"
                          ? "flex size-7 items-center justify-center rounded-full bg-blue-500 text-[11px] font-semibold text-white"
                          : "flex size-7 items-center justify-center rounded-full bg-[var(--tf-bg-soft)] text-[11px] font-semibold text-[var(--tf-text)]"
                    }
                  >
                    {index + 1}
                  </span>
                  <div>
                    <p
                      className={
                        step.state === "complete"
                          ? "text-sm font-semibold text-emerald-800"
                          : step.state === "active"
                            ? "text-sm font-semibold text-blue-800"
                            : "text-sm font-semibold text-[var(--tf-text)]"
                      }
                    >
                      {step.title}
                    </p>
                    <p
                      className={
                        step.state === "complete"
                          ? "mt-0.5 text-[11px] text-emerald-700"
                          : step.state === "active"
                            ? "mt-0.5 text-[11px] text-blue-700"
                            : "mt-0.5 text-[11px] text-[var(--tf-text-subtle)]"
                      }
                    >
                      {step.state === "complete"
                        ? t("productGrid.stepStateComplete")
                        : step.state === "active"
                          ? t("productGrid.stepStateActive")
                          : t("productGrid.stepStatePending")}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {processBanner && (
          <div className={`mt-3 rounded-2xl border px-3 py-2.5 ${getBannerToneClasses(processBanner.tone)}`}>
            <div className="flex items-start gap-2">
              <ProcessBannerIcon tone={processBanner.tone} />
              <div className="min-w-0">
                <p className="text-xs font-semibold leading-5">{processBanner.title}</p>
                <p className="mt-1 text-xs leading-5">{processBanner.description}</p>
              </div>
            </div>
          </div>
        )}

        {currentCandidate && (
          <Card className="tf-summary-active mt-3 border-blue-200 bg-[linear-gradient(180deg,rgba(239,246,255,0.9),rgba(255,255,255,0.95))]">
            <CardContent className="p-3">
              <div className="flex items-start gap-3">
                <ImageWithFallback
                  src={currentCandidate.imageUrl}
                  alt={currentCandidate.title}
                  wrapperClassName="size-14 rounded-2xl shrink-0"
                  className="size-14 rounded-2xl"
                />
                <div className="min-w-0 flex-1">
                  <div className="flex items-center justify-between gap-2">
                    <p className="text-xs uppercase tracking-[0.18em] text-[var(--tf-text-subtle)]">{t("productGrid.currentProduct")}</p>
                    <span className="shrink-0 rounded-full border border-blue-200 bg-white px-2 py-0.5 text-[10px] font-medium text-blue-700">
                      {isAnalyzingReport ? t("productGrid.stepStateActive") : t("products.selected")}
                    </span>
                  </div>
                  <h3 className="mt-1 text-base font-semibold leading-tight text-[var(--tf-text)]">{getReadableProductName(currentCandidate.title)}</h3>
                  <p className="mt-1 text-xs leading-5 text-[var(--tf-text-muted)]">
                    {getReadableOriginalTitle(currentCandidate.title, getReadableProductName(currentCandidate.title))}
                  </p>
                  {currentReportBadges.length > 0 && (
                    <div className="mt-2 flex flex-wrap gap-1.5">
                      {currentReportBadges.map((badge) => (
                        <span
                          key={badge.key}
                          className="rounded-full border border-blue-200 bg-white px-2 py-1 text-[10px] font-medium leading-none text-blue-700"
                        >
                          {badge.value}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>
        )}
      </div>

      <div className="tradeflow-scrollbar min-h-0 flex-1 overflow-auto px-4 py-4">
        {isLoading && candidates.length === 0 ? (
          <div className="grid gap-3 lg:grid-cols-3">
            {Array.from({ length: 9 }).map((_, i) => (
              <div key={i} className="overflow-hidden rounded-[22px] border border-[var(--tf-border)] bg-[var(--tf-bg-soft)]">
                <div className="tf-skeleton aspect-[4/3]" />
                <div className="space-y-2 p-3">
                  <div className="tf-skeleton h-3 w-3/4 rounded" />
                  <div className="tf-skeleton h-3 w-1/2 rounded" />
                  <div className="tf-skeleton h-8 w-full rounded-xl" />
                </div>
              </div>
            ))}
          </div>
        ) : candidates.length === 0 ? (
          <div className="flex h-full min-h-[24rem] items-center justify-center text-center text-sm text-[var(--tf-text-subtle)]">
            {t("productGrid.empty")}
          </div>
        ) : (
          <div className="grid gap-3 lg:grid-cols-3">
            {candidates.map((candidate) => (
              <ProductCard
                key={candidate.productId}
                candidate={candidate}
                selected={selectedProductId === candidate.productId}
                analyzing={isAnalyzingReport}
                disabled={isAnalyzingReport}
                onAnalyze={analyzeProduct}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

function ProcessBannerIcon({ tone }: { tone: "info" | "warning" | "success" }) {
  switch (tone) {
    case "warning":
      return <AlertTriangle className="mt-0.5 size-4 shrink-0" />
    case "success":
      return <CheckCircle2 className="mt-0.5 size-4 shrink-0" />
    default:
      return <Clock3 className="mt-0.5 size-4 shrink-0" />
  }
}

function getBannerToneClasses(tone: "info" | "warning" | "success") {
  switch (tone) {
    case "warning":
      return "border-amber-200 bg-amber-50 text-amber-900"
    case "success":
      return "border-emerald-200 bg-emerald-50 text-emerald-900"
    default:
      return "border-sky-200 bg-sky-50 text-sky-900"
  }
}

// globalvibe-web/app/components/product/ProductGrid.vue
<script setup lang="ts">
import ProductCard from '~/components/product/ProductCard.vue'
import { getReadableOriginalTitle, getReadableProductName } from '~/utils/presentation'

const props = withDefaults(defineProps<{
  compact?: boolean
}>(), {
  compact: false,
})

const productsStore = useProductsStore()
const taskStore = useTaskStore()
const { analyzeProduct } = useTaskRunner()
const { t } = useAppI18n()
const containerRef = ref<HTMLElement | null>(null)
const topHeight = ref(22)

const gridCols = 'grid-cols-1 md:grid-cols-2 xl:grid-cols-3'

const workflowSteps = computed(() => {
  const hasCandidates = productsStore.filteredCandidates.length > 0
  const hasSelection = Boolean(productsStore.selectedProductId)
  const hasReport = Boolean(productsStore.currentReport) && !productsStore.isAnalyzingReport

  return [
    {
      key: 'discover',
      titleKey: 'products.stepDiscoverTitle',
      descriptionKey: 'products.stepDiscoverDescription',
      state: hasCandidates ? 'complete' : taskStore.isPolling ? 'active' : 'pending',
    },
    {
      key: 'select',
      titleKey: 'products.stepSelectTitle',
      descriptionKey: 'products.stepSelectDescription',
      state: hasSelection ? 'complete' : hasCandidates ? 'active' : 'pending',
    },
    {
      key: 'report',
      titleKey: 'products.stepReportTitle',
      descriptionKey: productsStore.isAnalyzingReport ? 'products.stepReportLoading' : 'products.stepReportDescription',
      state: hasReport ? 'complete' : productsStore.isAnalyzingReport ? 'active' : 'pending',
    },
  ] as const
})

const workflowCardClass = (state: 'pending' | 'active' | 'complete') => {
  if (state === 'complete') {
    return 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900/50 dark:bg-emerald-950/30 dark:text-emerald-300'
  }

  if (state === 'active') {
    return 'border-blue-200 bg-blue-50 text-blue-700 dark:border-blue-900/50 dark:bg-blue-950/30 dark:text-blue-300'
  }

  return 'border-slate-200 bg-white text-slate-500 dark:border-slate-800 dark:bg-slate-950/40 dark:text-slate-400'
}

const handleSelectProduct = (productId: string) => {
  if (productsStore.isAnalyzingReport) return
  void analyzeProduct(productId).catch(() => undefined)
}

const startResize = (event: MouseEvent) => {
  event.preventDefault()

  const handleMouseMove = (moveEvent: MouseEvent) => {
    const container = containerRef.value
    if (!container) return

    const rect = container.getBoundingClientRect()
    const next = ((moveEvent.clientY - rect.top) / rect.height) * 100
    topHeight.value = Math.min(58, Math.max(18, next))
  }

  const handleMouseUp = () => {
    document.removeEventListener('mousemove', handleMouseMove)
    document.removeEventListener('mouseup', handleMouseUp)
    document.body.style.cursor = ''
    document.body.style.userSelect = ''
  }

  document.addEventListener('mousemove', handleMouseMove)
  document.addEventListener('mouseup', handleMouseUp)
  document.body.style.cursor = 'row-resize'
  document.body.style.userSelect = 'none'
}

const selectedDisplayTitle = computed(() => {
  if (!productsStore.currentCandidate?.title) return ''
  return getReadableProductName(productsStore.currentCandidate.title)
})

const selectedOriginalTitle = computed(() => {
  if (!productsStore.currentCandidate?.title) return ''
  return getReadableOriginalTitle(productsStore.currentCandidate.title, selectedDisplayTitle.value)
})

const canResize = computed(() => !props.compact)
</script>

<template>
  <div ref="containerRef" class="flex h-full min-h-0 flex-col">
    <div
      class="tradeflow-scrollbar min-h-0 overflow-auto"
      :class="canResize ? 'border-b border-[var(--tf-border)]' : ''"
      :style="canResize ? { flexBasis: `${topHeight}%` } : undefined"
    >
      <div :class="[props.compact ? 'px-4 py-4' : 'px-4 py-4 xl:px-5']">
        <div class="flex items-start justify-between gap-4">
          <div>
            <div class="flex items-center gap-2">
              <UIcon name="i-heroicons-shopping-bag" class="h-5 w-5 text-slate-400 dark:text-slate-500" />
              <span class="text-lg font-semibold text-slate-800 dark:text-slate-100">{{ t('products.title') }}</span>
              <span v-if="productsStore.filteredCandidates.length > 0" class="ml-1 text-sm text-slate-400 dark:text-slate-500">
                {{ t('products.count', { count: productsStore.filteredCandidates.length }) }}
              </span>
            </div>
            <p class="mt-1 max-w-2xl text-[13px] leading-5 text-slate-500 dark:text-slate-400">
              {{ t('products.subtitle') }}
            </p>
          </div>

          <span
            v-if="taskStore.status !== 'IDLE'"
            class="rounded-full border border-[var(--tf-border)] bg-white/80 px-3 py-1 text-[12px] text-slate-600 dark:bg-slate-950/80 dark:text-slate-300"
          >
            {{ t(`stage.${taskStore.stage}`) }}
          </span>
        </div>

        <div class="mt-3 flex flex-wrap gap-2.5">
          <div
            v-for="(step, index) in workflowSteps"
            :key="step.key"
            :class="[
              'min-w-[11rem] flex-1 rounded-2xl border px-3.5 py-3 transition-colors',
              workflowCardClass(step.state),
            ]"
          >
            <div class="flex items-center gap-2">
              <span class="flex h-6 w-6 items-center justify-center rounded-full bg-white/80 text-[11px] font-semibold dark:bg-slate-900/60">
                {{ index + 1 }}
              </span>
              <p class="text-sm font-semibold">{{ t(step.titleKey) }}</p>
            </div>
            <p class="mt-1.5 text-[12px] leading-5 opacity-90">
              {{ t(step.descriptionKey) }}
            </p>
          </div>
        </div>

        <div
          v-if="productsStore.filteredCandidates.length > 0"
          class="mt-3 rounded-2xl border border-[var(--tf-border)] bg-[var(--tf-bg-soft)] px-4 py-2.5 text-[13px] text-slate-600 dark:text-slate-300"
        >
          {{ productsStore.isAnalyzingReport ? t('products.selectionHint') : t('products.selectionReady') }}
        </div>

        <div
          v-if="productsStore.currentCandidate"
          class="tradeflow-panel mt-3 rounded-[var(--tf-radius-xl)] px-4 py-3.5"
        >
          <div class="flex flex-col gap-3 xl:flex-row xl:items-start">
            <div class="flex h-14 w-14 items-center justify-center overflow-hidden rounded-xl bg-slate-100 dark:bg-slate-800">
              <img
                v-if="productsStore.currentCandidate.imageUrl"
                :src="productsStore.currentCandidate.imageUrl"
                :alt="productsStore.currentCandidate.title"
                class="h-14 w-14 object-cover"
              />
              <UIcon v-else name="i-heroicons-photo" class="h-8 w-8 text-slate-400 dark:text-slate-600" />
            </div>

            <div class="min-w-0 flex-1">
              <p class="tradeflow-section-title">
                {{ t('products.selectedTitle') }}
              </p>
              <h3 class="mt-1.5 text-[17px] font-semibold leading-6 text-slate-900 dark:text-slate-100">
                {{ selectedDisplayTitle }}
              </h3>
              <p v-if="selectedOriginalTitle" class="mt-1 line-clamp-1 text-[13px] leading-5 text-slate-500 dark:text-slate-400">
                {{ selectedOriginalTitle }}
              </p>
              <p class="mt-1.5 text-[13px] leading-5 text-slate-500 dark:text-slate-400">
                {{
                  productsStore.isAnalyzingReport
                    ? t('products.selectedDescriptionLoading', { title: selectedDisplayTitle })
                    : t('products.selectedDescriptionReady', { title: selectedDisplayTitle })
                }}
              </p>
              <p v-if="productsStore.currentCandidate.recommendationReason" class="mt-2 line-clamp-2 text-[13px] leading-5 text-slate-500 dark:text-slate-400">
                {{ productsStore.currentCandidate.recommendationReason }}
              </p>
            </div>

            <div class="grid grid-cols-3 gap-3 text-[12px] text-slate-500 xl:min-w-[15rem] xl:text-right dark:text-slate-400">
              <div>
                <p>{{ t('products.price') }}</p>
                <p class="mt-1 font-semibold text-slate-700 dark:text-slate-200">
                  ${{ productsStore.currentCandidate.overseasPrice ?? '--' }}
                </p>
              </div>
              <div>
                <p>{{ t('products.margin') }}</p>
                <p class="mt-1 font-semibold text-emerald-600 dark:text-emerald-400">
                  {{ productsStore.currentCandidate.estimatedMargin !== null ? `+${productsStore.currentCandidate.estimatedMargin}%` : '--' }}
                </p>
              </div>
              <div>
                <p>{{ t('products.riskTag') }}</p>
                <p class="mt-1 font-semibold text-slate-700 dark:text-slate-200">
                  {{ productsStore.currentCandidate.riskTag ?? '--' }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <button
      v-if="canResize"
      type="button"
      aria-label="Resize product panels"
      class="group flex h-4 shrink-0 cursor-row-resize items-center justify-center bg-white/70 transition-colors hover:bg-slate-100 dark:bg-slate-900/70 dark:hover:bg-slate-800"
      @mousedown="startResize"
    >
      <span class="h-1 w-14 rounded-full bg-slate-300 transition-colors group-hover:bg-slate-400 dark:bg-slate-700 dark:group-hover:bg-slate-500" />
    </button>

    <div :class="['tradeflow-scrollbar overflow-auto', canResize ? 'min-h-0 flex-1 p-4 xl:p-5' : 'p-4 pt-0 md:p-5 md:pt-0']">
      <div v-if="productsStore.isLoading && productsStore.filteredCandidates.length === 0" :class="['grid gap-6', gridCols]">
        <div
          v-for="i in 8"
          :key="i"
          class="animate-pulse rounded-xl bg-slate-100 p-4 dark:bg-slate-900"
        >
          <div class="aspect-square rounded-lg bg-slate-200 dark:bg-slate-800" />
          <div class="mt-3 h-4 rounded bg-slate-200 dark:bg-slate-800" />
          <div class="mt-2 h-4 w-2/3 rounded bg-slate-200 dark:bg-slate-800" />
        </div>
      </div>

      <div
        v-else-if="productsStore.filteredCandidates.length === 0"
        class="flex h-full flex-col items-center justify-center text-center"
      >
        <UIcon name="i-heroicons-cube" class="h-16 w-16 text-slate-300 dark:text-slate-700" />
        <h3 class="mt-4 text-lg font-medium text-slate-600 dark:text-slate-400">{{ t('products.emptyTitle') }}</h3>
        <p class="mt-2 max-w-xs text-sm leading-relaxed text-slate-400 dark:text-slate-500">
          {{ t('products.emptyDescription') }}
        </p>
      </div>

      <div v-else :class="['grid gap-3.5 xl:gap-4', gridCols]">
        <ProductCard
          v-for="product in productsStore.filteredCandidates"
          :key="product.productId"
          :product="product"
          :is-selected="productsStore.selectedProductId === product.productId"
          :is-analyzing="productsStore.isAnalyzingReport && productsStore.selectedProductId === product.productId"
          :is-disabled="productsStore.isAnalyzingReport"
          @select="handleSelectProduct"
        />
      </div>
    </div>
  </div>
</template>
