// tradeflow-web-next/src/components/report/thinking-log.tsx
"use client"

import { useEffect, useMemo, useRef, useState } from "react"

import { Button } from "@/components/ui/button"
import { useAppI18n } from "@/components/layout/locale-provider"
import { useAgentStore } from "@/stores/agent-store"
import { useTaskStore } from "@/stores/task-store"
import { getLiveStageMessage, humanizeTaskLog, isKeyTaskLog, resolveTaskLogCategory } from "@/lib/presentation"

function formatTaskTime(timestamp: string) {
  const date = new Date(timestamp)
  if (Number.isNaN(date.getTime())) return "--:--:--"
  const hh = String(date.getHours()).padStart(2, "0")
  const mm = String(date.getMinutes()).padStart(2, "0")
  const ss = String(date.getSeconds()).padStart(2, "0")
  return `${hh}:${mm}:${ss}`
}

export function ThinkingLog() {
  const { t } = useAppI18n()
  const logs = useAgentStore((state) => state.taskLogs)
  const isPolling = useTaskStore((state) => state.isPolling)
  const stage = useTaskStore((state) => state.stage)
  const [filter, setFilter] = useState<"all" | "key">("all")
  const [typedLengths, setTypedLengths] = useState<Record<string, number>>({})
  const [autoFollowEnabled, setAutoFollowEnabled] = useState(true)

  const visibleLogs = useMemo(() => (filter === "all" ? logs : logs.filter(isKeyTaskLog)), [filter, logs])

  const containerRef = useRef<HTMLDivElement>(null)
  const isUserScrolledRef = useRef(false)
  const previousKeysRef = useRef<string[]>([])

  const keyedLogs = useMemo(
    () =>
      visibleLogs.map((entry, index) => {
        const key = `${entry.timestamp}-${entry.stage}-${index}`
        return { key, entry, view: humanizeTaskLog(entry), category: resolveTaskLogCategory(entry) }
      }),
    [visibleLogs],
  )

  useEffect(() => {
    const el = containerRef.current
    if (!el) return
    const onScroll = () => {
      const nextUserScrolled = el.scrollTop + el.clientHeight < el.scrollHeight - 40
      isUserScrolledRef.current = nextUserScrolled
      setAutoFollowEnabled(!nextUserScrolled)
    }
    onScroll()
    el.addEventListener("scroll", onScroll, { passive: true })
    return () => el.removeEventListener("scroll", onScroll)
  }, [])

  useEffect(() => {
    if (!isUserScrolledRef.current && containerRef.current) {
      containerRef.current.scrollTop = containerRef.current.scrollHeight
    }
  }, [keyedLogs, typedLengths, isPolling])

  useEffect(() => {
    const nextKeys = keyedLogs.map((item) => item.key)
    const previousKeys = previousKeysRef.current

    if (previousKeys.length === 0) {
      previousKeysRef.current = nextKeys
      return
    }

    const appended = keyedLogs.filter((item) => !previousKeys.includes(item.key))
    if (!appended.length) {
      previousKeysRef.current = nextKeys
      return
    }

    const latest = appended[appended.length - 1]
    setTypedLengths((current) => {
      const next = { ...current }
      appended.slice(0, -1).forEach((item) => {
        next[item.key] = item.view.message.length
      })
      next[latest.key] = 0
      return next
    })

    let revealed = 0
    const fullLength = latest.view.message.length
    const timer = window.setInterval(() => {
      revealed = Math.min(fullLength, revealed + 2)
      setTypedLengths((current) => ({ ...current, [latest.key]: revealed }))
      if (revealed >= fullLength) {
        window.clearInterval(timer)
      }
    }, 18)

    previousKeysRef.current = nextKeys
    return () => window.clearInterval(timer)
  }, [keyedLogs])

  if (!visibleLogs.length) {
    return (
      <div className="flex h-full min-h-[14rem] items-center justify-center px-6 text-sm text-[var(--tf-text-subtle)]">
        {t("analysisPanel.emptyLogs")}
      </div>
    )
  }

  return (
    <div className="flex h-full min-h-0 flex-col">
      <div className="flex items-center justify-between border-b border-[var(--tf-border)] px-3 py-2">
        <div className="inline-flex rounded-xl border border-[var(--tf-border)] bg-white p-0.5">
          <Button
            size="sm"
            variant={filter === "all" ? "secondary" : "ghost"}
            className="h-8 rounded-lg px-2.5 text-xs"
            onClick={() => setFilter("all")}
          >
            {t("logs.filterAll")}
          </Button>
          <Button
            size="sm"
            variant={filter === "key" ? "secondary" : "ghost"}
            className="h-8 rounded-lg px-2.5 text-xs"
            onClick={() => setFilter("key")}
          >
            {t("logs.filterKey")}
          </Button>
        </div>
        <span className="text-[11px] text-[var(--tf-text-subtle)]">
          {autoFollowEnabled ? t("logs.autoFollowOn") : t("logs.autoFollowOff")}
        </span>
      </div>
      <div ref={containerRef} className="tradeflow-scrollbar h-full overflow-auto px-3 py-3">
        <div className="space-y-2">
          {keyedLogs.map(({ key, entry, view, category }) => {
            const typed = typedLengths[key]
            const message = typeof typed === "number" ? view.message.slice(0, typed) : view.message
            const isStillTyping = typeof typed === "number" && typed < view.message.length
            return (
              <div
                key={key}
                className={[
                  "tf-log-entry rounded-2xl border p-3",
                  category === "alert"
                    ? "border-amber-200 bg-amber-50"
                    : "border-[var(--tf-border)] bg-[var(--tf-bg-soft)]",
                ].join(" ")}
              >
                <div className="mb-1 flex items-center justify-between gap-2 text-[11px] text-[var(--tf-text-subtle)]">
                  <span>{view.stageLabel}</span>
                  <span>{formatTaskTime(entry.timestamp)}</span>
                </div>
                <p className="text-xs leading-5 text-[var(--tf-text)]">
                  {message}
                  {isStillTyping && <span className="ml-0.5 inline-block animate-pulse">▋</span>}
                </p>
              </div>
            )
          })}
          {isPolling && (
            <div className="rounded-2xl border border-blue-200 bg-blue-50 p-3">
              <p className="text-xs text-blue-700">
                {getLiveStageMessage(stage)}
                <span className="ml-1 inline-block animate-pulse">▋</span>
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// globalvibe-web/app/components/report/ThinkingLog.vue
<script setup lang="ts">
import type { LogFilterMode } from '~/types'
import { getLiveStageMessage, humanizeTaskLog, isKeyTaskLog, resolveTaskLogCategory } from '~/utils/presentation'

const agentStore = useAgentStore()
const taskStore = useTaskStore()
const { t } = useAppI18n()
const logContainer = ref<HTMLElement | null>(null)
const liveTimestamp = ref('')
const displayedLengths = reactive<Record<string, number>>({})
const typingStates = reactive<Record<string, boolean>>({})
const animationTimers = new Map<string, ReturnType<typeof setInterval>>()
const autoFollow = ref(true)
const filterMode = ref<LogFilterMode>('all')

const entryKey = (entry: { timestamp: string, stage: string }, index: number) => `${entry.timestamp}-${entry.stage}-${index}`

const scrollToBottom = (behavior: ScrollBehavior = 'smooth') => {
  if (!autoFollow.value || !logContainer.value) return
  logContainer.value.scrollTo({
    top: logContainer.value.scrollHeight,
    behavior,
  })
}

const syncAutoFollow = () => {
  if (!logContainer.value) return
  const remaining = logContainer.value.scrollHeight - logContainer.value.scrollTop - logContainer.value.clientHeight
  autoFollow.value = remaining < 56
}

const animateMessage = (key: string, content: string) => {
  const existingTimer = animationTimers.get(key)
  if (existingTimer) clearInterval(existingTimer)

  displayedLengths[key] = 0
  typingStates[key] = true
  const timer = setInterval(() => {
    displayedLengths[key] = Math.min(content.length, displayedLengths[key] + 1)
    scrollToBottom('smooth')

    if (displayedLengths[key] >= content.length) {
      clearInterval(timer)
      animationTimers.delete(key)
      typingStates[key] = false
    }
  }, 18)

  animationTimers.set(key, timer)
}

const levelColors: Record<string, string> = {
  INFO: 'text-slate-600 dark:text-slate-300',
  WARN: 'text-amber-600 dark:text-amber-400',
  WARNING: 'text-amber-600 dark:text-amber-400',
  ERROR: 'text-red-600 dark:text-red-400',
}

const formatTime = (date: string) => new Date(date).toLocaleTimeString()

const getEntryView = (entry: (typeof agentStore.taskLogs)[number]) => humanizeTaskLog(entry)
const getEntryCategory = (entry: (typeof agentStore.taskLogs)[number]) => resolveTaskLogCategory(entry)

const visibleLogs = computed(() => {
  if (filterMode.value === 'key') {
    return agentStore.taskLogs.filter(isKeyTaskLog)
  }
  return agentStore.taskLogs
})

const getDisplayedMessage = (entry: (typeof agentStore.taskLogs)[number], index: number) => {
  const key = entryKey(entry, index)
  const content = getEntryView(entry).message
  const length = displayedLengths[key] ?? 0
  return content.slice(0, length)
}

onMounted(() => {
  liveTimestamp.value = new Date().toLocaleTimeString()
})

onUnmounted(() => {
  animationTimers.forEach(timer => clearInterval(timer))
  animationTimers.clear()
})

watch(
  () => visibleLogs.value.map((entry, index) => ({
    key: entryKey(entry, index),
    message: humanizeTaskLog(entry).message,
  })),
  (entries) => {
    if (!entries.length) {
      return
    }

    entries.forEach(entry => {
      if (!(entry.key in displayedLengths)) {
        animateMessage(entry.key, entry.message)
      }
    })

    nextTick(() => scrollToBottom('smooth'))
  },
  { deep: true },
)

watch(
  () => taskStore.isPolling,
  (isPolling) => {
    if (isPolling) {
      liveTimestamp.value = new Date().toLocaleTimeString()
      nextTick(() => scrollToBottom('smooth'))
    }
  }
)
</script>

<template>
  <div
    ref="logContainer"
    class="tradeflow-scrollbar h-full overflow-y-auto px-3 py-2.5 text-sm text-slate-500 dark:text-slate-400"
    style="scroll-behavior: smooth"
    @scroll="syncAutoFollow"
  >
    <div class="sticky top-0 z-10 mb-2.5 rounded-2xl border border-[var(--tf-border)] bg-[var(--tf-bg-panel)]/95 px-3 py-2.5 backdrop-blur">
      <div class="flex flex-wrap items-center justify-between gap-3">
        <div class="inline-flex rounded-2xl border border-[var(--tf-border)] bg-white/70 p-1 text-sm dark:bg-slate-950/70">
          <button
            type="button"
            class="rounded-xl px-3 py-2 transition"
            :class="filterMode === 'all' ? 'bg-[var(--tf-accent-soft)] text-[var(--tf-text)]' : 'text-slate-500 dark:text-slate-400'"
            @click="filterMode = 'all'"
          >
            {{ t('logs.filterAll') }}
          </button>
          <button
            type="button"
            class="rounded-xl px-3 py-2 transition"
            :class="filterMode === 'key' ? 'bg-[var(--tf-accent-soft)] text-[var(--tf-text)]' : 'text-slate-500 dark:text-slate-400'"
            @click="filterMode = 'key'"
          >
            {{ t('logs.filterKey') }}
          </button>
        </div>

        <button
          type="button"
          class="inline-flex items-center gap-2 rounded-xl border border-[var(--tf-border)] bg-white/70 px-3 py-1.5 text-sm font-medium text-slate-600 transition hover:bg-white dark:bg-slate-950/70 dark:text-slate-300"
          @click="autoFollow = !autoFollow"
        >
          <span class="h-2 w-2 rounded-full" :class="autoFollow ? 'bg-emerald-500' : 'bg-slate-400'" />
          {{ autoFollow ? t('logs.autoFollowOn') : t('logs.autoFollowOff') }}
        </button>
      </div>
    </div>

    <div v-if="visibleLogs.length === 0" class="flex h-full items-center justify-center">
      <div class="rounded-lg bg-slate-100 p-4 dark:bg-slate-900">
        <p class="text-slate-400 dark:text-slate-500">{{ t('logs.empty') }}</p>
      </div>
    </div>

    <div v-else class="space-y-1.5">
      <div
        v-for="(entry, index) in visibleLogs"
        :key="`${entry.timestamp}-${entry.stage}-${index}`"
        class="tradeflow-log-entry flex gap-3 rounded-2xl px-3 py-2.5"
        :class="getEntryCategory(entry) === 'alert'
          ? 'border border-amber-200 bg-amber-50/90 dark:border-amber-900/50 dark:bg-amber-950/20'
          : getEntryCategory(entry) === 'system'
            ? 'border border-[var(--tf-border)] bg-[var(--tf-bg-soft)]'
            : 'border border-blue-100 bg-blue-50/65 dark:border-blue-900/40 dark:bg-blue-950/20'"
      >
        <span class="flex-shrink-0 font-mono text-slate-400 dark:text-slate-500">{{ formatTime(entry.timestamp) }}</span>

        <div class="flex-1">
          <p class="mb-1 text-[12px] font-semibold tracking-wide text-slate-400 dark:text-slate-500">
            {{ getEntryView(entry).stageLabel }}
          </p>
          <span :class="['leading-6', levelColors[entry.level] ?? 'text-slate-600 dark:text-slate-300']">
            {{ getDisplayedMessage(entry, index) }}
            <span
              v-if="typingStates[entryKey(entry, index)]"
              class="ml-0.5 inline-block animate-pulse text-blue-500 dark:text-blue-300"
            >
              |
            </span>
          </span>
        </div>
      </div>

      <div v-if="taskStore.isPolling" class="flex gap-3 rounded-2xl border border-blue-100 bg-blue-50/70 px-3 py-2.5 dark:border-slate-800 dark:bg-slate-900">
        <span class="flex-shrink-0 font-mono text-slate-400 dark:text-slate-500">{{ liveTimestamp }}</span>
        <div class="text-slate-500 dark:text-slate-400">
          <p class="text-[11px] font-semibold tracking-wide text-slate-400 dark:text-slate-500">{{ t('logs.running') }}</p>
          <span class="leading-6">
            {{ getLiveStageMessage(taskStore.stage) }}<span class="animate-pulse">...</span>
          </span>
        </div>
      </div>
    </div>
  </div>
</template>
