// tradeflow-web-next/src/app/reports/page.tsx
"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import { ArrowRight } from "lucide-react"

import { AppShell } from "@/components/layout/app-shell"
import { useAppI18n } from "@/components/layout/locale-provider"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { getReportList } from "@/lib/api/report"
import { getReadableOriginalTitle, getReadableProductName, humanizeQualityTier, humanizeReportSource } from "@/lib/presentation"
import type { ReportListItem } from "@/types"

function formatPercent(value?: number | null) {
  if (value === null || value === undefined || Number.isNaN(value)) return "--"
  return `${Number(value).toFixed(1)}%`
}

export default function ReportsPage() {
  const { t } = useAppI18n()
  const [reports, setReports] = useState<ReportListItem[]>([])

  useEffect(() => {
    void getReportList()
      .then((response) => setReports(response.items))
      .catch(() => setReports([]))
  }, [])

  return (
    <AppShell activePanel="reports">
      <div className="mx-auto max-w-6xl">
        <h1 className="text-2xl font-semibold text-[var(--tf-text)]">{t("reportsPage.title")}</h1>
        <p className="mt-2 text-sm text-[var(--tf-text-muted)]">{t("reportsPage.subtitle")}</p>

        {reports.length === 0 ? (
          <Card className="mt-8">
            <CardContent className="p-6 text-sm text-[var(--tf-text-muted)]">{t("reportsPage.empty")}</CardContent>
          </Card>
        ) : (
          <div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
            {reports.map((report) => {
              const title = getReadableProductName(report.title)
              const original = getReadableOriginalTitle(report.title, title)
              return (
                <div
                  key={report.reportId}
                  className="tradeflow-card rounded-[var(--tf-radius-xl)] p-5 transition hover:-translate-y-0.5 hover:border-[var(--tf-border-strong)]"
                >
                  <Link href={`/reports/${report.reportId}`} className="block">
                    <p className="text-base font-semibold text-[var(--tf-text)]">{title}</p>
                    {original && <p className="mt-1 line-clamp-2 text-xs leading-6 text-[var(--tf-text-muted)]">{original}</p>}
                    <div className="mt-4 flex flex-wrap gap-2 text-[11px] text-[var(--tf-text-muted)]">
                      <span className="rounded-full border border-[var(--tf-border)] px-2 py-1">{t(`decision.${report.decision}`)}</span>
                      <span className="rounded-full border border-[var(--tf-border)] px-2 py-1">{t(`risk.${report.riskLevel}`)}</span>
                      {report.qualityTier && (
                        <span className="rounded-full border border-[var(--tf-border)] px-2 py-1">
                          {humanizeQualityTier(report.qualityTier, t)}
                        </span>
                      )}
                      <span className="rounded-full border border-[var(--tf-border)] px-2 py-1">
                        {t("report.fallback")}: {report.fallbackUsed ? t("common.yes") : t("common.no")}
                      </span>
                    </div>
                    <div className="mt-3 grid grid-cols-2 gap-2">
                      <div className="rounded-xl border border-[var(--tf-border)] bg-white/80 px-3 py-2">
                        <p className="text-[10px] text-[var(--tf-text-subtle)]">{t("report.expectedMargin")}</p>
                        <p className="mt-1 text-sm font-semibold text-emerald-600">{formatPercent(report.margin)}</p>
                      </div>
                      <div className="rounded-xl border border-[var(--tf-border)] bg-white/80 px-3 py-2">
                        <p className="text-[10px] text-[var(--tf-text-subtle)]">{t("report.matchSource")}</p>
                        <p className="mt-1 line-clamp-2 text-xs font-medium text-[var(--tf-text)]">{humanizeReportSource(report.retrievalSource, t)}</p>
                      </div>
                    </div>
                    {report.detailSource && (
                      <p className="mt-3 text-xs text-[var(--tf-text-muted)]">
                        {t("report.detailSource")}: {humanizeReportSource(report.detailSource, t)}
                      </p>
                    )}
                    <p className="mt-3 text-xs text-[var(--tf-text-subtle)]">{new Date(report.generatedAt).toLocaleString()}</p>
                  </Link>
                  <div className="mt-4">
                    <Link href={`/?taskId=${report.taskId}&reportId=${report.reportId}`}>
                      <Button variant="outline" size="sm">
                        {t("productGrid.openWorkbench")}
                        <ArrowRight className="size-4" />
                      </Button>
                    </Link>
                  </div>
                </div>
              )
            })}
          </div>
        )}
      </div>
    </AppShell>
  )
}

// globalvibe-web/app/pages/reports.vue
<script setup lang="ts">
import { getReportList } from '~/services/report'
import type { ReportListItem } from '~/types'
import { getReadableOriginalTitle, getReadableProductName, humanizeQualityTier, humanizeReportSource } from '~/utils/presentation'

const { t } = useAppI18n()
const reports = ref<ReportListItem[]>([])

onMounted(async () => {
  try {
    const response = await getReportList()
    reports.value = response.items
  } catch {
    reports.value = []
  }
})

const displayTitle = (title: string) => getReadableProductName(title)
const originalTitle = (title: string) => getReadableOriginalTitle(title, displayTitle(title))
const formatPercent = (value?: number | null) => {
  if (value === null || value === undefined || Number.isNaN(value)) return '--'
  return `${Number(value).toFixed(1)}%`
}
const formatSignedPercent = (value?: number | null) => {
  if (value === null || value === undefined || Number.isNaN(value)) return '--'
  const prefix = value > 0 ? '+' : ''
  return `${prefix}${formatPercent(value)}`
}
</script>

<template>
  <div class="tradeflow-scrollbar min-h-[calc(100dvh-4.5rem)] overflow-auto p-4 md:p-6 xl:p-8">
    <div class="mx-auto max-w-6xl">
      <h1 class="text-2xl font-semibold text-slate-800 dark:text-slate-100">{{ t('reportsPage.title') }}</h1>
      <p class="mt-2 text-sm text-slate-500 dark:text-slate-400">{{ t('reportsPage.subtitle') }}</p>

      <div v-if="reports.length === 0" class="tradeflow-card mt-8 rounded-[var(--tf-radius-xl)] p-6 text-sm text-slate-500 dark:text-slate-400">
        {{ t('reportsPage.empty') }}
      </div>

      <div v-else class="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        <NuxtLink
          v-for="report in reports"
          :key="report.reportId"
          :to="`/reports/${report.reportId}`"
          class="tradeflow-card rounded-[var(--tf-radius-xl)] p-5 transition hover:-translate-y-0.5 hover:border-[var(--tf-border-strong)]"
        >
          <p class="text-base font-semibold text-slate-800 dark:text-slate-100">{{ displayTitle(report.title) }}</p>
          <p v-if="originalTitle(report.title)" class="mt-1 line-clamp-2 text-xs leading-6 text-slate-500 dark:text-slate-400">
            {{ originalTitle(report.title) }}
          </p>
          <div class="mt-4 flex items-center justify-between text-xs text-slate-500 dark:text-slate-400">
            <span>{{ t(`decision.${report.decision}`) }}</span>
            <span>{{ t(`risk.${report.riskLevel}`) }}</span>
          </div>
          <div class="mt-3 flex flex-wrap gap-2">
            <span class="rounded-full border border-slate-200 px-2.5 py-1 text-[11px] font-semibold text-slate-600 dark:border-slate-700 dark:text-slate-300">
              {{ t('report.qualityTier') }} {{ humanizeQualityTier(report.qualityTier, t) }}
            </span>
            <span class="rounded-full border border-slate-200 px-2.5 py-1 text-[11px] font-semibold text-slate-600 dark:border-slate-700 dark:text-slate-300">
              {{ t('report.fallback') }} {{ t(report.fallbackUsed ? 'common.yes' : 'common.no') }}
            </span>
          </div>
          <p class="mt-3 text-lg font-semibold text-green-600 dark:text-green-400">{{ formatSignedPercent(report.margin) }}</p>
          <div class="mt-3 space-y-1 text-[11px] text-slate-400 dark:text-slate-500">
            <p>{{ t('report.matchSource') }}: {{ humanizeReportSource(report.retrievalSource, t) }}</p>
            <p v-if="report.detailSource">{{ t('report.detailSource') }}: {{ humanizeReportSource(report.detailSource, t) }}</p>
          </div>
          <p class="mt-3 text-xs text-slate-400 dark:text-slate-500">{{ new Date(report.generatedAt).toLocaleString() }}</p>
        </NuxtLink>
      </div>
    </div>
  </div>
</template>
