// tradeflow-web-next/src/app/settings/page.tsx
"use client"

import { useEffect, useState } from "react"

import { AppShell } from "@/components/layout/app-shell"
import { useAppI18n } from "@/components/layout/locale-provider"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { getDemoConfig } from "@/lib/api/settings"
import { useSettingsStore } from "@/stores/settings-store"
import type { DemoConfigResponse } from "@/types"

export default function SettingsPage() {
  const { locale, setLocale, t } = useAppI18n()
  const settingsStore = useSettingsStore()
  const [config, setConfig] = useState<DemoConfigResponse | null>(null)
  const [saved, setSaved] = useState(false)

  useEffect(() => {
    settingsStore.hydrate()
    void getDemoConfig().then(setConfig).catch(() => setConfig(null))
  }, [settingsStore])

  const saveSettings = () => {
    setLocale(settingsStore.locale)
    setSaved(true)
    window.setTimeout(() => setSaved(false), 1500)
  }

  return (
    <AppShell activePanel="settings">
      <div className="mx-auto max-w-3xl">
        <h1 className="text-2xl font-semibold text-[var(--tf-text)]">{t("settings.title")}</h1>
        <p className="mt-2 text-sm text-[var(--tf-text-muted)]">{t("settings.subtitle")}</p>

        <div className="mt-8 space-y-5">
          <Card>
            <CardContent className="p-5">
              <label htmlFor="settings-language" className="text-sm font-medium text-[var(--tf-text)]">
                {t("settings.language")}
              </label>
              <select
                id="settings-language"
                className="mt-3 flex h-12 w-full rounded-2xl border border-[var(--tf-border)] bg-white px-4 text-sm text-[var(--tf-text)] outline-none"
                value={locale}
                onChange={(event) => {
                  const nextLocale = event.target.value === "en" ? "en" : "zh-CN"
                  settingsStore.patchSettings({ locale: nextLocale })
                  setLocale(nextLocale)
                }}
              >
                <option value="zh-CN">中文</option>
                <option value="en">English</option>
              </select>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-5">
              <label htmlFor="settings-market" className="text-sm font-medium text-[var(--tf-text)]">
                {t("settings.defaultMarket")}
              </label>
              <select
                id="settings-market"
                className="mt-3 flex h-12 w-full rounded-2xl border border-[var(--tf-border)] bg-white px-4 text-sm text-[var(--tf-text)] outline-none"
                value={settingsStore.defaultMarket}
                onChange={(event) => settingsStore.patchSettings({ defaultMarket: event.target.value })}
              >
                {(config?.markets ?? ["AmazonUS"]).map((market) => (
                  <option key={market} value={market}>
                    {market}
                  </option>
                ))}
              </select>
            </CardContent>
          </Card>

          <Button onClick={saveSettings}>{t("settings.save")}</Button>
          {saved && <p className="text-sm text-green-600">{t("settings.savedHint")}</p>}
        </div>
      </div>
    </AppShell>
  )
}

// globalvibe-web/app/pages/settings.vue
<script setup lang="ts">
import AppSelect from '~/components/ui/AppSelect.vue'
import type { AppLocale } from '~/stores/locale'
import { getDemoConfig } from '~/services/settings'
import type { DemoConfigResponse } from '~/types'

const { t, locale, setLocale } = useAppI18n()
const settingsStore = useSettingsStore()
const config = ref<DemoConfigResponse | null>(null)
const saved = ref(false)
const defaultMarket = computed({
  get: () => settingsStore.settings.defaultMarket,
  set: (value: string) => settingsStore.patchSettings({ defaultMarket: value }),
})
const currentLocale = computed({
  get: () => locale.value,
  set: (value: string) => updateLocale(value as AppLocale),
})
const localeOptions = [
  { value: 'zh-CN', label: '中文' },
  { value: 'en', label: 'English' },
]

onMounted(async () => {
  try {
    config.value = await getDemoConfig()
  } catch {
    config.value = null
  }
})

const saveSettings = () => {
  settingsStore.save()
  setLocale(settingsStore.settings.locale)
  saved.value = true
  setTimeout(() => {
    saved.value = false
  }, 1500)
}

const updateLocale = (value: AppLocale) => {
  settingsStore.patchSettings({ locale: value })
  setLocale(value)
}

</script>

<template>
  <NuxtLayout name="default">
    <div class="tradeflow-scrollbar h-full overflow-auto p-8">
      <h1 class="text-2xl font-semibold text-slate-800 dark:text-slate-100">{{ t('settings.title') }}</h1>
      <p class="mt-2 text-sm text-slate-500 dark:text-slate-400">{{ t('settings.subtitle') }}</p>

      <div class="mt-8 max-w-2xl space-y-5">
        <div class="rounded-2xl bg-white p-5 ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-800">
          <label for="settings-language" class="text-sm font-medium text-slate-700 dark:text-slate-300">{{ t('settings.language') }}</label>
          <AppSelect id="settings-language" v-model="currentLocale" :options="localeOptions" class="mt-3" />
        </div>

        <div class="rounded-2xl bg-white p-5 ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-800">
          <label for="settings-market" class="text-sm font-medium text-slate-700 dark:text-slate-300">{{ t('settings.defaultMarket') }}</label>
          <AppSelect id="settings-market" v-model="defaultMarket" :options="config?.markets ?? []" class="mt-3" />
        </div>
        <button
          type="button"
          class="rounded-lg bg-blue-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-blue-500"
          @click="saveSettings"
        >
          {{ t('settings.save') }}
        </button>

        <p v-if="saved" class="text-sm text-green-600 dark:text-green-400">{{ t('settings.savedHint') }}</p>
      </div>
    </div>
  </NuxtLayout>
</template>
