// tradeflow-web-next/src/components/layout/sidebar.tsx
"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import { Boxes, ClipboardList, History, Settings2 } from "lucide-react"

import { useAppI18n } from "@/components/layout/locale-provider"
import { cn } from "@/lib/utils"
import { useUIStore } from "@/stores/ui-store"

const items = [
  { key: "workspace", href: "/", icon: Boxes, labelKey: "nav.workspace" },
  { key: "history", href: "/history", icon: History, labelKey: "nav.history" },
  { key: "reports", href: "/reports", icon: ClipboardList, labelKey: "nav.reports" },
  { key: "settings", href: "/settings", icon: Settings2, labelKey: "nav.settings" },
] as const

export function Sidebar() {
  const { t } = useAppI18n()
  const activePanel = useUIStore((state) => state.activePanel)
  const setActivePanel = useUIStore((state) => state.setActivePanel)
  const pathname = usePathname()

  return (
    <aside className="flex h-full w-16 shrink-0 flex-col items-center gap-2 border-r border-[var(--tf-border)] bg-[var(--tf-bg-panel)] px-2 py-4">
      <div className="flex size-10 items-center justify-center rounded-2xl bg-[var(--tf-accent-soft)] text-xs font-bold text-[var(--tf-accent-strong)]">
        TF
      </div>
      <div className="mt-2 flex flex-col gap-1.5">
        {items.map((item) => {
          const Icon = item.icon
          const active =
            pathname === item.href || (item.href !== "/" && pathname.startsWith(`${item.href}/`)) || activePanel === item.key
          return (
            <Link
              key={item.key}
              href={item.href}
              onClick={() => setActivePanel(item.key)}
              className={cn(
                "flex size-10 items-center justify-center rounded-2xl border transition",
                active
                  ? "border-transparent bg-[var(--tf-accent-soft)] text-[var(--tf-accent-strong)]"
                  : "border-transparent text-[var(--tf-text-subtle)] hover:bg-[var(--tf-bg-soft)] hover:text-[var(--tf-text)]",
              )}
              title={t(item.labelKey)}
            >
              <Icon className="size-5" />
            </Link>
          )
        })}
      </div>
    </aside>
  )
}

// globalvibe-web/app/components/layout/Sidebar.vue
<script setup lang="ts">
const { t } = useAppI18n()
const route = useRoute()

const menuItems = [
  { icon: 'i-heroicons-sparkles', to: '/', labelKey: 'nav.workspace' },
  { icon: 'i-heroicons-clock', to: '/history', labelKey: 'nav.history' },
  { icon: 'i-heroicons-document-chart-bar', to: '/reports', labelKey: 'nav.reports' },
  { icon: 'i-heroicons-cog-6-tooth', to: '/settings', labelKey: 'nav.settings' },
]
</script>

<template>
  <div class="flex h-full flex-col items-center py-4">
    <div class="mb-6 flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-200 dark:bg-slate-900">
      <span class="text-sm font-bold tracking-tight text-slate-600 dark:text-slate-300">GV</span>
    </div>

    <nav class="flex flex-1 flex-col items-center gap-1">
      <NuxtLink
        v-for="item in menuItems"
        :key="item.to"
        :to="item.to"
        :aria-label="t(item.labelKey)"
        :class="[
          'group flex h-10 w-10 items-center justify-center rounded-xl transition-all duration-200',
          route.path === item.to
            ? 'bg-slate-200 text-slate-800 dark:bg-slate-800 dark:text-slate-200'
            : 'text-slate-400 hover:bg-slate-100 hover:text-slate-600 dark:text-slate-500 dark:hover:bg-slate-800/50 dark:hover:text-slate-300',
        ]"
      >
        <UIcon :name="item.icon" class="h-[18px] w-[18px]" />
      </NuxtLink>
    </nav>
  </div>
</template>
