// globalvibe-web/app/pages/reports/[reportId].vue
<script setup lang="ts">
import ArbitrageReport from '~/components/report/ArbitrageReport.vue'
import { getReportByReportId } from '~/services/report'
import type { ReportDetail } from '~/types'

const route = useRoute()
const { t } = useAppI18n()
const report = ref<ReportDetail | null>(null)
const isLoading = ref(true)
const errorMessage = ref('')

onMounted(async () => {
  try {
    report.value = await getReportByReportId(String(route.params.reportId))
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : 'Failed to load report'
  } finally {
    isLoading.value = false
  }
})
</script>

<template>
  <div class="tradeflow-scrollbar min-h-[calc(100dvh-4.5rem)] overflow-auto p-4 md:p-6 xl:p-8">
    <div class="mx-auto max-w-6xl">
      <div class="flex items-center gap-3">
        <NuxtLink
          to="/reports"
          class="inline-flex items-center gap-2 rounded-2xl border border-[var(--tf-border)] bg-white/80 px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-white dark:bg-slate-900 dark:text-slate-200"
        >
          <UIcon name="i-heroicons-arrow-left" class="h-4 w-4" />
          {{ t('reportsPage.backToList') }}
        </NuxtLink>
      </div>

      <div v-if="errorMessage" class="mt-6 rounded-2xl bg-red-50 p-6 text-sm text-red-700 ring-1 ring-red-100 dark:bg-red-950/30 dark:text-red-200 dark:ring-red-900/50">
        {{ errorMessage }}
      </div>

      <div v-else class="tradeflow-panel mt-6 overflow-hidden rounded-[var(--tf-radius-2xl)]">
        <ArbitrageReport
          :report="report"
          :candidate-title="report?.title ?? null"
          :is-loading="isLoading"
        />
      </div>
    </div>
  </div>
</template>

// tradeflow-web-next/src/app/reports/[reportId]/page.tsx
"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import { ArrowLeft } from "lucide-react"

import { AppShell } from "@/components/layout/app-shell"
import { ArbitrageReport } from "@/components/report/arbitrage-report"
import { Button } from "@/components/ui/button"
import { getReportByReportId } from "@/lib/api/report"
import type { ReportDetail } from "@/types"

export default function ReportDetailPage({ params }: { params: Promise<{ reportId: string }> }) {
  const [report, setReport] = useState<ReportDetail | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [errorMessage, setErrorMessage] = useState("")

  useEffect(() => {
    let alive = true
    void params.then(({ reportId }) => {
      void getReportByReportId(reportId)
        .then((next) => {
          if (alive) setReport(next)
        })
        .catch((error) => {
          if (alive) setErrorMessage(error instanceof Error ? error.message : "Failed to load report")
        })
        .finally(() => {
          if (alive) setIsLoading(false)
        })
    })
    return () => {
      alive = false
    }
  }, [params])

  return (
    <AppShell activePanel="reports">
      <div className="mx-auto flex min-h-full max-w-6xl flex-col">
        <div className="flex items-center gap-3">
          <Link href="/reports">
            <Button variant="outline" size="sm">
              <ArrowLeft className="size-4" />
              返回报告列表
            </Button>
          </Link>
          {report && (
            <Link href={`/?taskId=${report.taskId}&reportId=${report.reportId}`}>
              <Button variant="outline" size="sm">
                在工作台中打开
              </Button>
            </Link>
          )}
        </div>

        {errorMessage ? (
          <div className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">{errorMessage}</div>
        ) : (
          <div className="tradeflow-panel mt-6 min-h-0 flex-1 overflow-auto rounded-[var(--tf-radius-2xl)]">
            <ArbitrageReport report={report} candidateTitle={report?.title ?? null} isLoading={isLoading} />
          </div>
        )}
      </div>
    </AppShell>
  )
}
